version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
  go-gin-4:
    container_name: go-gin-4
    build:
      context: .
      dockerfile: Dockerfile
    image: go-gin-4:latest
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    
volumes:
  postgres-data:
    name: postgres-data